moved public constants at top closer together

diff --git a/trunk/source/2.1/src/shell/shunit2 b/trunk/source/2.1/src/shell/shunit2
--- a/trunk/source/2.1/src/shell/shunit2
+++ b/trunk/source/2.1/src/shell/shunit2
@@ -20,13 +20,13 @@
 
 SHUNIT_VERSION='2.1.5pre'
 
-_shunit_warn() { echo "shunit2:WARN $@" >&2; }
-_shunit_error() { echo "shunit2:ERROR $@" >&2; }
-_shunit_fatal() { echo "shunit2:FATAL $@" >&2; }
-
 SHUNIT_TRUE=0
 SHUNIT_FALSE=1
 SHUNIT_ERROR=2
+
+_shunit_warn() { echo "shunit2:WARN $@" >&2; }
+_shunit_error() { echo "shunit2:ERROR $@" >&2; }
+_shunit_fatal() { echo "shunit2:FATAL $@" >&2; }
 
 # specific shell checks
 if [ -n "${ZSH_VERSION:-}" ]; then
