Fixed shellcheck warnings.

diff --git a/shunit2_test_helpers b/shunit2_test_helpers
--- a/shunit2_test_helpers
+++ b/shunit2_test_helpers
@@ -7,6 +7,11 @@
 #
 # Author: kate.ward@forestent.com (Kate Ward)
 # https://github.com/kward/shunit2
+#
+# $() are not fully portable (POSIX != portable).
+#   shellcheck disable=SC2006
+# expr may be antiquated, but it is the only solution in some cases.
+#   shellcheck disable=SC2003
 
 # Treat unset variables as an error when performing parameter expansion.
 set -u
@@ -19,7 +24,7 @@ set -u
 #
 
 # Path to shUnit2 library. Can be overridden by setting SHUNIT_INC.
-TH_SHUNIT=${SHUNIT_INC:-./shunit2}
+export TH_SHUNIT=${SHUNIT_INC:-./shunit2}
 
 # Configure debugging. Set the DEBUG environment variable to any
 # non-empty value to enable debug output, or TRACE to enable trace
@@ -42,22 +47,22 @@ th_RANDOM=0
 #
 
 # Logging functions.
-th_trace() { echo "${MY_NAME}:TRACE $@" >&2; }
-th_debug() { echo "${MY_NAME}:DEBUG $@" >&2; }
-th_info() { echo "${MY_NAME}:INFO $@" >&2; }
-th_warn() { echo "${MY_NAME}:WARN $@" >&2; }
-th_error() { echo "${MY_NAME}:ERROR $@" >&2; }
-th_fatal() { echo "${MY_NAME}:FATAL $@" >&2; }
+th_trace() { echo "${MY_NAME}:TRACE $*" >&2; }
+th_debug() { echo "${MY_NAME}:DEBUG $*" >&2; }
+th_info() { echo "${MY_NAME}:INFO $*" >&2; }
+th_warn() { echo "${MY_NAME}:WARN $*" >&2; }
+th_error() { echo "${MY_NAME}:ERROR $*" >&2; }
+th_fatal() { echo "${MY_NAME}:FATAL $*" >&2; }
 
 # Output subtest name.
-th_subtest() { echo " $@" >&2; }
+th_subtest() { echo " $*" >&2; }
 
 th_oneTimeSetUp() {
   # These files will be cleaned up automatically by shUnit2.
-  stdoutF="${SHUNIT_TMPDIR}/stdout"
-  stderrF="${SHUNIT_TMPDIR}/stderr"
-  returnF="${SHUNIT_TMPDIR}/return"
-  expectedF="${SHUNIT_TMPDIR}/expected"
+  export stdoutF="${SHUNIT_TMPDIR}/stdout"
+  export stderrF="${SHUNIT_TMPDIR}/stderr"
+  export returnF="${SHUNIT_TMPDIR}/return"
+  export expectedF="${SHUNIT_TMPDIR}/expected"
 }
 
 # Generate a random number.
@@ -72,7 +77,7 @@ th_generateRandom() {
       tfgr_random=`od -vAn -N4 -tu4 </dev/urandom |sed 's/^[^0-9]*//'`
     else
       tfgr_date=`date '+%H%M%S'`
-      tfgr_random=`expr ${tfgr_date} \* $$`
+      tfgr_random=`expr "${tfgr_date}" \* $$`
       unset tfgr_date
     fi
     \[ "${tfgr_random}" = "${th_RANDOM}" ] && sleep 1
@@ -95,6 +100,7 @@ th_sgrep() {
   th_pattern_=$1
   shift
 
+  # shellcheck disable=SC2068
   sed -e '/./{H;$!d;}' -e "x;/${th_pattern_}/"'!d;' $@ |sed '1d'
 
   unset th_pattern_
@@ -115,8 +121,8 @@ th_assertTrueWithNoOutput() {
   th_stdout_=$3
   th_stderr_=$4
 
-  assertTrue "${th_test_}; expected return value of zero" ${th_rtrn_}
-  \[ ${th_rtrn_} -ne ${SHUNIT_TRUE} ] && \cat "${th_stderr_}"
+  assertTrue "${th_test_}; expected return value of zero" "${th_rtrn_}"
+  \[ "${th_rtrn_}" -ne "${SHUNIT_TRUE}" ] && \cat "${th_stderr_}"
   assertFalse "${th_test_}; expected no output to STDOUT" \
       "[ -s '${th_stdout_}' ]"
   assertFalse "${th_test_}; expected no output to STDERR" \
@@ -140,13 +146,13 @@ th_assertFalseWithOutput()
   th_stdout_=$3
   th_stderr_=$4
 
-  assertFalse "${th_test_}; expected non-zero return value" ${th_rtrn_}
+  assertFalse "${th_test_}; expected non-zero return value" "${th_rtrn_}"
   assertTrue "${th_test_}; expected output to STDOUT" \
       "[ -s '${th_stdout_}' ]"
   assertFalse "${th_test_}; expected no output to STDERR" \
       "[ -s '${th_stderr_}' ]"
   \[ -s "${th_stdout_}" -a ! -s "${th_stderr_}" ] || \
-      _th_showOutput ${SHUNIT_FALSE} "${th_stdout_}" "${th_stderr_}"
+      _th_showOutput "${SHUNIT_FALSE}" "${th_stdout_}" "${th_stderr_}"
 
   unset th_test_ th_rtrn_ th_stdout_ th_stderr_
 }
@@ -165,13 +171,13 @@ th_assertFalseWithError() {
   th_stdout_=$3
   th_stderr_=$4
 
-  assertFalse "${th_test_}; expected non-zero return value" ${th_rtrn_}
+  assertFalse "${th_test_}; expected non-zero return value" "${th_rtrn_}"
   assertFalse "${th_test_}; expected no output to STDOUT" \
       "[ -s '${th_stdout_}' ]"
   assertTrue "${th_test_}; expected output to STDERR" \
       "[ -s '${th_stderr_}' ]"
   \[ ! -s "${th_stdout_}" -a -s "${th_stderr_}" ] || \
-      _th_showOutput ${SHUNIT_FALSE} "${th_stdout_}" "${th_stderr_}"
+      _th_showOutput "${SHUNIT_FALSE}" "${th_stdout_}" "${th_stderr_}"
 
   unset th_test_ th_rtrn_ th_stdout_ th_stderr_
 }
@@ -186,17 +192,18 @@ th_queryReturn() {
   else
     th_return=${SHUNIT_ERROR}
   fi
+  export th_return
 }
 
 # Providing external and internal calls to the showOutput helper function.
-th_showOutput() { _th_showOutput $@; }
+th_showOutput() { _th_showOutput "$@"; }
 _th_showOutput() {
   _th_return_=$1
   _th_stdout_=$2
   _th_stderr_=$3
 
   isSkipping
-  if \[ $? -eq ${SHUNIT_FALSE} -a ${_th_return_} != ${SHUNIT_TRUE} ]; then
+  if \[ $? -eq "${SHUNIT_FALSE}" -a "${_th_return_}" != "${SHUNIT_TRUE}" ]; then
     if \[ -n "${_th_stdout_}" -a -s "${_th_stdout_}" ]; then
       echo '>>> STDOUT' >&2
       \cat "${_th_stdout_}" >&2
