Fixed shellcheck warnings. Also fixed a few other minor issues.

diff --git a/shunit2 b/shunit2
--- a/shunit2
+++ b/shunit2
@@ -1,7 +1,7 @@
 #! /bin/sh
 # vim:et:ft=sh:sts=2:sw=2
 #
-# Copyright 2008 Kate Ward. All Rights Reserved.
+# Copyright 2008-2017 Kate Ward. All Rights Reserved.
 # Released under the Apache 2.0 license.
 #
 # shUnit2 -- Unit testing framework for Unix shell scripts.
@@ -12,8 +12,11 @@
 # shUnit2 is a xUnit based unit test framework for Bourne shell scripts. It is
 # based on the popular JUnit unit testing framework for Java.
 #
-# Disable ShellCheck checks that aren't fully portable (POSIX != portable).
+### Disable ShellCheck checks.
+## $() are not fully portable (POSIX != portable).
 # shellcheck disable=SC2006
+## expr may be antiquated, but it is the only solution in some cases.
+# shellcheck disable=SC2003
 
 # Return if shunit2 already loaded.
 \[ -n "${SHUNIT_VERSION:-}" ] && exit 0
@@ -25,9 +28,9 @@ SHUNIT_FALSE=1
 SHUNIT_ERROR=2
 
 # Logging functions.
-_shunit_warn() { echo "shunit2:WARN $@" >&2; }
-_shunit_error() { echo "shunit2:ERROR $@" >&2; }
-_shunit_fatal() { echo "shunit2:FATAL $@" >&2; exit ${SHUNIT_ERROR}; }
+_shunit_warn() { echo "shunit2:WARN $*" >&2; }
+_shunit_error() { echo "shunit2:ERROR $*" >&2; }
+_shunit_fatal() { echo "shunit2:FATAL $*" >&2; exit ${SHUNIT_ERROR}; }
 
 # Determine some reasonable command defaults.
 __SHUNIT_UNAME_S=`uname -s`
@@ -37,6 +40,7 @@ case "${__SHUNIT_UNAME_S}" in
 esac
 
 __SHUNIT_CMD_ECHO_ESC='echo -e'
+# shellcheck disable=SC2039
 \[ "`echo -e test`" = '-e test' ] && __SHUNIT_CMD_ECHO_ESC='echo'
 
 # Commands a user can override if needed.
@@ -72,6 +76,7 @@ __SHUNIT_PARENT=${SHUNIT_PARENT:-$0}
 __SHUNIT_ANSI_NONE='\033[0m'
 __SHUNIT_ANSI_RED='\033[1;31m'
 __SHUNIT_ANSI_GREEN='\033[1;32m'
+__SHUNIT_ANSI_YELLOW='\033[1;33m'
 __SHUNIT_ANSI_CYAN='\033[1;36m'
 
 # Set the constants readonly.
@@ -80,11 +85,11 @@ echo "${__shunit_constants}" |grep '^Binary file' >/dev/null && \
     __shunit_constants=`set |grep -a '^__SHUNIT_' |cut -d= -f1`
 for __shunit_const in ${__shunit_constants}; do
   if \[ -z "${ZSH_VERSION:-}" ]; then
-    readonly ${__shunit_const}
+    readonly "${__shunit_const}"
   else
     case ${ZSH_VERSION} in
-      [123].*) readonly ${__shunit_const} ;;
-      *) readonly -g ${__shunit_const}  # Declare readonly constants globally.
+      [123].*) readonly "${__shunit_const}" ;;
+      *) readonly -g "${__shunit_const}"  # Declare readonly constants globally.
     esac
   fi
 done
@@ -106,6 +111,7 @@ __shunit_suite=''  # Suite of tests to execute.
 __shunit_ansi_none=''
 __shunit_ansi_red=''
 __shunit_ansi_green=''
+__shunit_ansi_yellow=''
 __shunit_ansi_cyan=''
 
 # Counts of tests.
@@ -124,6 +130,7 @@ __shunit_assertsSkipped=0
 # Macros.
 #
 
+# shellcheck disable=SC2016,SC2089
 _SHUNIT_LINENO_='eval __shunit_lineno=""; if \[ "${1:-}" = "--lineno" ]; then \[ -n "$2" ] && __shunit_lineno="[$2] "; shift 2; fi'
 
 #-----------------------------------------------------------------------------
@@ -139,6 +146,7 @@ _SHUNIT_LINENO_='eval __shunit_lineno=""; if \[ "${1:-}" = "--lineno" ]; then \[
 # Returns:
 #   integer: success (TRUE/FALSE/ERROR constant)
 assertEquals() {
+  # shellcheck disable=SC2090
   ${_SHUNIT_LINENO_}
   if \[ $# -lt 2 -o $# -gt 3 ]; then
     _shunit_error "assertEquals() requires two or three arguments; $# given"
@@ -166,6 +174,7 @@ assertEquals() {
   unset shunit_message_ shunit_expected_ shunit_actual_
   return ${shunit_return}
 }
+# shellcheck disable=SC2016,SC2034
 _ASSERT_EQUALS_='eval assertEquals --lineno "${LINENO:-}"'
 
 # Assert that two values are not equal to one another.
@@ -177,6 +186,7 @@ _ASSERT_EQUALS_='eval assertEquals --lineno "${LINENO:-}"'
 # Returns:
 #   integer: success (TRUE/FALSE/ERROR constant)
 assertNotEquals() {
+  # shellcheck disable=SC2090
   ${_SHUNIT_LINENO_}
   if \[ $# -lt 2 -o $# -gt 3 ]; then
     _shunit_error "assertNotEquals() requires two or three arguments; $# given"
@@ -203,6 +213,7 @@ assertNotEquals() {
   unset shunit_message_ shunit_expected_ shunit_actual_
   return ${shunit_return}
 }
+# shellcheck disable=SC2016,SC2034
 _ASSERT_NOT_EQUALS_='eval assertNotEquals --lineno "${LINENO:-}"'
 
 # Assert that a value is null (i.e. an empty string)
@@ -213,6 +224,7 @@ _ASSERT_NOT_EQUALS_='eval assertNotEquals --lineno "${LINENO:-}"'
 # Returns:
 #   integer: success (TRUE/FALSE/ERROR constant)
 assertNull() {
+  # shellcheck disable=SC2090
   ${_SHUNIT_LINENO_}
   if \[ $# -lt 1 -o $# -gt 2 ]; then
     _shunit_error "assertNull() requires one or two arguments; $# given"
@@ -231,6 +243,7 @@ assertNull() {
   unset shunit_message_
   return ${shunit_return}
 }
+# shellcheck disable=SC2016,SC2034
 _ASSERT_NULL_='eval assertNull --lineno "${LINENO:-}"'
 
 # Assert that a value is not null (i.e. a non-empty string)
@@ -242,6 +255,7 @@ _ASSERT_NULL_='eval assertNull --lineno "${LINENO:-}"'
 #   integer: success (TRUE/FALSE/ERROR constant)
 assertNotNull()
 {
+  # shellcheck disable=SC2090
   ${_SHUNIT_LINENO_}
   if \[ $# -gt 2 ]; then  # allowing 0 arguments as $1 might actually be null
     _shunit_error "assertNotNull() requires one or two arguments; $# given"
@@ -262,6 +276,7 @@ assertNotNull()
   unset shunit_actual_ shunit_message_
   return ${shunit_return}
 }
+# shellcheck disable=SC2016,SC2034
 _ASSERT_NOT_NULL_='eval assertNotNull --lineno "${LINENO:-}"'
 
 # Assert that two values are the same (i.e. equal to one another).
@@ -273,6 +288,7 @@ _ASSERT_NOT_NULL_='eval assertNotNull --lineno "${LINENO:-}"'
 # Returns:
 #   integer: success (TRUE/FALSE/ERROR constant)
 assertSame() {
+  # shellcheck disable=SC2090
   ${_SHUNIT_LINENO_}
   if \[ $# -lt 2 -o $# -gt 3 ]; then
     _shunit_error "assertSame() requires two or three arguments; $# given"
@@ -291,6 +307,7 @@ assertSame() {
   unset shunit_message_
   return ${shunit_return}
 }
+# shellcheck disable=SC2016,SC2034
 _ASSERT_SAME_='eval assertSame --lineno "${LINENO:-}"'
 
 # Assert that two values are not the same (i.e. not equal to one another).
@@ -302,6 +319,7 @@ _ASSERT_SAME_='eval assertSame --lineno "${LINENO:-}"'
 # Returns:
 #   integer: success (TRUE/FALSE/ERROR constant)
 assertNotSame() {
+  # shellcheck disable=SC2090
   ${_SHUNIT_LINENO_}
   if \[ $# -lt 2 -o $# -gt 3 ]; then
     _shunit_error "assertNotSame() requires two or three arguments; $# given"
@@ -320,6 +338,7 @@ assertNotSame() {
   unset shunit_message_
   return ${shunit_return}
 }
+# shellcheck disable=SC2016,SC2034
 _ASSERT_NOT_SAME_='eval assertNotSame --lineno "${LINENO:-}"'
 
 # Assert that a value or shell test condition is true.
@@ -344,6 +363,7 @@ _ASSERT_NOT_SAME_='eval assertNotSame --lineno "${LINENO:-}"'
 # Returns:
 #   integer: success (TRUE/FALSE/ERROR constant)
 assertTrue() {
+  # shellcheck disable=SC2090
   ${_SHUNIT_LINENO_}
   if \[ $# -lt 1 -o $# -gt 2 ]; then
     _shunit_error "assertTrue() takes one or two arguments; $# given"
@@ -367,10 +387,10 @@ assertTrue() {
   elif \[ -n "${shunit_match_}" -a "${shunit_condition_}" = "${shunit_match_}" ]
   then
     # Possible return value. Treating 0 as true, and non-zero as false.
-    \[ ${shunit_condition_} -ne 0 ] && shunit_return=${SHUNIT_FALSE}
+    \[ "${shunit_condition_}" -ne 0 ] && shunit_return=${SHUNIT_FALSE}
   else
     # Hopefully... a condition.
-    ( eval ${shunit_condition_} ) >/dev/null 2>&1
+    ( eval "${shunit_condition_}" ) >/dev/null 2>&1
     \[ $? -ne 0 ] && shunit_return=${SHUNIT_FALSE}
   fi
 
@@ -384,6 +404,7 @@ assertTrue() {
   unset shunit_message_ shunit_condition_ shunit_match_
   return ${shunit_return}
 }
+# shellcheck disable=SC2016,SC2034
 _ASSERT_TRUE_='eval assertTrue --lineno "${LINENO:-}"'
 
 # Assert that a value or shell test condition is false.
@@ -408,6 +429,7 @@ _ASSERT_TRUE_='eval assertTrue --lineno "${LINENO:-}"'
 # Returns:
 #   integer: success (TRUE/FALSE/ERROR constant)
 assertFalse() {
+  # shellcheck disable=SC2090
   ${_SHUNIT_LINENO_}
   if \[ $# -lt 1 -o $# -gt 2 ]; then
     _shunit_error "assertFalse() quires one or two arguments; $# given"
@@ -431,23 +453,24 @@ assertFalse() {
   elif \[ -n "${shunit_match_}" -a "${shunit_condition_}" = "${shunit_match_}" ]
   then
     # Possible return value. Treating 0 as true, and non-zero as false.
-    \[ ${shunit_condition_} -eq 0 ] && shunit_return=${SHUNIT_FALSE}
+    \[ "${shunit_condition_}" -eq 0 ] && shunit_return=${SHUNIT_FALSE}
   else
     # Hopefully... a condition.
-    ( eval ${shunit_condition_} ) >/dev/null 2>&1
+    ( eval "${shunit_condition_}" ) >/dev/null 2>&1
     \[ $? -eq 0 ] && shunit_return=${SHUNIT_FALSE}
   fi
 
   # Record the test.
-  if \[ ${shunit_return} -eq ${SHUNIT_TRUE} ]; then
+  if \[ "${shunit_return}" -eq "${SHUNIT_TRUE}" ]; then
     _shunit_assertPass
   else
     _shunit_assertFail "${shunit_message_}"
   fi
 
   unset shunit_message_ shunit_condition_ shunit_match_
-  return ${shunit_return}
+  return "${shunit_return}"
 }
+# shellcheck disable=SC2016,SC2034
 _ASSERT_FALSE_='eval assertFalse --lineno "${LINENO:-}"'
 
 #-----------------------------------------------------------------------------
@@ -461,6 +484,7 @@ _ASSERT_FALSE_='eval assertFalse --lineno "${LINENO:-}"'
 # Returns:
 #   integer: success (TRUE/FALSE/ERROR constant)
 fail() {
+  # shellcheck disable=SC2090
   ${_SHUNIT_LINENO_}
   if \[ $# -gt 1 ]; then
     _shunit_error "fail() requires zero or one arguments; $# given"
@@ -479,6 +503,7 @@ fail() {
   unset shunit_message_
   return ${SHUNIT_FALSE}
 }
+# shellcheck disable=SC2016,SC2034
 _FAIL_='eval fail --lineno "${LINENO:-}"'
 
 # Records a test failure, stating two values were not equal.
@@ -490,6 +515,7 @@ _FAIL_='eval fail --lineno "${LINENO:-}"'
 # Returns:
 #   integer: success (TRUE/FALSE/ERROR constant)
 failNotEquals() {
+  # shellcheck disable=SC2090
   ${_SHUNIT_LINENO_}
   if \[ $# -lt 2 -o $# -gt 3 ]; then
     _shunit_error "failNotEquals() requires one or two arguments; $# given"
@@ -510,6 +536,7 @@ failNotEquals() {
   unset shunit_message_ shunit_expected_ shunit_actual_
   return ${SHUNIT_FALSE}
 }
+# shellcheck disable=SC2016,SC2034
 _FAIL_NOT_EQUALS_='eval failNotEquals --lineno "${LINENO:-}"'
 
 # Records a test failure, stating two values should have been the same.
@@ -522,6 +549,7 @@ _FAIL_NOT_EQUALS_='eval failNotEquals --lineno "${LINENO:-}"'
 #   integer: success (TRUE/FALSE/ERROR constant)
 failSame()
 {
+  # shellcheck disable=SC2090
   ${_SHUNIT_LINENO_}
   if \[ $# -lt 2 -o $# -gt 3 ]; then
     _shunit_error "failSame() requires two or three arguments; $# given"
@@ -540,6 +568,7 @@ failSame()
   unset shunit_message_
   return ${SHUNIT_FALSE}
 }
+# shellcheck disable=SC2016,SC2034
 _FAIL_SAME_='eval failSame --lineno "${LINENO:-}"'
 
 # Records a test failure, stating two values were not equal.
@@ -553,6 +582,7 @@ _FAIL_SAME_='eval failSame --lineno "${LINENO:-}"'
 # Returns:
 #   integer: success (TRUE/FALSE/ERROR constant)
 failNotSame() {
+  # shellcheck disable=SC2090
   ${_SHUNIT_LINENO_}
   if \[ $# -lt 2 -o $# -gt 3 ]; then
     _shunit_error "failNotEquals() requires one or two arguments; $# given"
@@ -571,6 +601,7 @@ failNotSame() {
   unset shunit_message_
   return ${shunit_return}
 }
+# shellcheck disable=SC2016,SC2034
 _FAIL_NOT_SAME_='eval failNotSame --lineno "${LINENO:-}"'
 
 #-----------------------------------------------------------------------------
@@ -591,10 +622,7 @@ startSkipping() { __shunit_skip=${SHUNIT_TRUE}; }
 #
 # Args:
 #   None
-endSkipping()
-{
-  __shunit_skip=${SHUNIT_FALSE}
-}
+endSkipping() { __shunit_skip=${SHUNIT_FALSE}; }
 
 # Returns the state of assert and fail call skipping.
 #
@@ -602,10 +630,7 @@ endSkipping()
 #   None
 # Returns:
 #   boolean: (TRUE/FALSE constant)
-isSkipping()
-{
-  return ${__shunit_skip}
-}
+isSkipping() { return ${__shunit_skip}; }
 
 #-----------------------------------------------------------------------------
 # Suite functions.
@@ -709,6 +734,7 @@ _shunit_mktempDir() {
   ( exec mktemp -dqt shunit.XXXXXX 2>/dev/null ) && return
 
   # The standard `mktemp` didn't work. Use our own.
+  # shellcheck disable=SC2039
   if \[ -r '/dev/urandom' -a -x '/usr/bin/od' ]; then
     _shunit_random_=`/usr/bin/od -vAn -N4 -tx4 </dev/urandom \
         |sed 's/^[^0-9a-f]*//'`
@@ -718,14 +744,14 @@ _shunit_mktempDir() {
   else
     # `$RANDOM` doesn't work.
     _shunit_date_=`date '+%Y%m%d%H%M%S'`
-    _shunit_random_=`expr ${_shunit_date_} / $$`
+    _shunit_random_=`expr "${_shunit_date_}" / $$`
   fi
 
   _shunit_tmpDir_="${TMPDIR:-/tmp}/shunit.${_shunit_random_}"
   ( umask 077 && \mkdir "${_shunit_tmpDir_}" ) || \
       _shunit_fatal 'could not create temporary directory! exiting'
 
-  echo ${_shunit_tmpDir_}
+  echo "${_shunit_tmpDir_}"
   unset _shunit_date_ _shunit_random_ _shunit_tmpDir_
 }
 
@@ -773,12 +799,12 @@ _shunit_cleanup()
   \rm -fr "${__shunit_tmpDir}"
 
   # Exit for all non-EXIT signals.
-  if \[ ${_shunit_name_} != 'EXIT' ]; then
+  if \[ "${_shunit_name_}" != 'EXIT' ]; then
     _shunit_warn "trapped and now handling the (${_shunit_name_}) signal"
     # Disable EXIT trap.
     trap 0
     # Add 128 to signal and exit.
-    exit `expr ${_shunit_signal_} + 128`
+    exit "`expr "${_shunit_signal_}" + 128`"
   elif \[ ${__shunit_reportGenerated} -eq ${SHUNIT_FALSE} ] ; then
     _shunit_assertFail 'Unknown failure encountered running a test'
     _shunit_generateReport
@@ -800,7 +826,8 @@ _shunit_configureColor() {
       ( exec tput >/dev/null 2>&1 )  # Check for existence of tput command.
       if [ $? -lt 127 ]; then
         _shunit_tput_=`tput colors`
-        [ $? -eq 0 -a ${_shunit_tput_} -ge 16 ] && _shunit_color_=${SHUNIT_TRUE}
+        # shellcheck disable=SC2166,SC2181
+        [ $? -eq 0 -a "${_shunit_tput_}" -ge 16 ] && _shunit_color_=${SHUNIT_TRUE}
       fi
       ;;
     'none') ;;
@@ -812,12 +839,14 @@ _shunit_configureColor() {
       __shunit_ansi_none=${__SHUNIT_ANSI_NONE}
       __shunit_ansi_red=${__SHUNIT_ANSI_RED}
       __shunit_ansi_green=${__SHUNIT_ANSI_GREEN}
+      __shunit_ansi_yellow=${__SHUNIT_ANSI_YELLOW}
       __shunit_ansi_cyan=${__SHUNIT_ANSI_CYAN}
       ;;
     ${SHUNIT_FALSE})
       __shunit_ansi_none=''
       __shunit_ansi_red=''
       __shunit_ansi_green=''
+      __shunit_ansi_yellow=''
       __shunit_ansi_cyan=''
       ;;
   esac
@@ -841,7 +870,7 @@ _shunit_execSuite() {
 
     # execute the test
     echo "${_shunit_test_}"
-    eval ${_shunit_test_}
+    eval "${_shunit_test_}"
 
     # execute the per-test tear-down function
     tearDown
@@ -867,15 +896,16 @@ _shunit_generateReport() {
   _shunit_ok_=${SHUNIT_TRUE}
 
   # If no exit code was provided one, determine an appropriate one.
-  \[ ${__shunit_testsFailed} -gt 0 \
+  \[ "${__shunit_testsFailed}" -gt 0 \
       -o ${__shunit_testSuccess} -eq ${SHUNIT_FALSE} ] \
           && _shunit_ok_=${SHUNIT_FALSE}
 
   echo
-  if \[ ${__shunit_testsTotal} -eq 1 ]; then
-    echo "Ran ${__shunit_testsTotal} test."
+  _shunit_msg_="Ran ${__shunit_ansi_cyan}${__shunit_testsTotal}${__shunit_ansi_none}"
+  if \[ "${__shunit_testsTotal}" -eq 1 ]; then
+    ${__SHUNIT_CMD_ECHO_ESC} "${_shunit_msg_} test."
   else
-    ${__SHUNIT_CMD_ECHO_ESC} "Ran ${__shunit_ansi_cyan}${__shunit_testsTotal}${__shunit_ansi_none} tests."
+    ${__SHUNIT_CMD_ECHO_ESC} "${_shunit_msg_} tests."
   fi
 
   _shunit_failures_=''
@@ -886,18 +916,19 @@ _shunit_generateReport() {
       && _shunit_skipped_="skipped=${__shunit_assertsSkipped}"
 
   if \[ ${_shunit_ok_} -eq ${SHUNIT_TRUE} ]; then
-    _shunit_msg_='OK'
+    _shunit_msg_="${__shunit_ansi_green}OK${__shunit_ansi_none}"
     \[ -n "${_shunit_skipped_}" ] \
-        && _shunit_msg_="${_shunit_msg_} (${_shunit_skipped_})"
+        && _shunit_msg_="${_shunit_msg_} (${__shunit_ansi_yellow}${_shunit_skipped_}${__shunit_ansi_none})"
   else
-    _shunit_msg_="FAILED (${_shunit_failures_}"
+    _shunit_msg_="${__shunit_ansi_red}FAILED${__shunit_ansi_none}"
+    _shunit_msg_="${_shunit_msg_} (${__shunit_ansi_red}${_shunit_failures_}${__shunit_ansi_none}"
     \[ -n "${_shunit_skipped_}" ] \
-        && _shunit_msg_="${_shunit_msg_},${_shunit_skipped_}"
+        && _shunit_msg_="${_shunit_msg_},${__shunit_ansi_yellow}${_shunit_skipped_}${__shunit_ansi_none}"
     _shunit_msg_="${_shunit_msg_})"
   fi
 
   echo
-  ${__SHUNIT_CMD_ECHO_ESC} "${_shunit_msg_}${__shunit_ansi_none}"
+  ${__SHUNIT_CMD_ECHO_ESC} "${_shunit_msg_}"
   __shunit_reportGenerated=${SHUNIT_TRUE}
 
   unset _shunit_failures_ _shunit_msg_ _shunit_ok_ _shunit_skipped_
@@ -932,8 +963,8 @@ _shunit_assertFail() {
   _shunit_msg_=$1
 
   __shunit_testSuccess=${SHUNIT_FALSE}
-  __shunit_assertsFailed=`expr ${__shunit_assertsFailed} + 1`
-  __shunit_assertsTotal=`expr ${__shunit_assertsTotal} + 1`
+  __shunit_assertsFailed=`expr "${__shunit_assertsFailed}" + 1`
+  __shunit_assertsTotal=`expr "${__shunit_assertsTotal}" + 1`
   ${__SHUNIT_CMD_ECHO_ESC} \
       "${__shunit_ansi_red}ASSERT:${__shunit_ansi_none}${_shunit_msg_}"
 
@@ -946,8 +977,8 @@ _shunit_assertFail() {
 #   None
 _shunit_assertSkip()
 {
-  __shunit_assertsSkipped=`expr ${__shunit_assertsSkipped} + 1`
-  __shunit_assertsTotal=`expr ${__shunit_assertsTotal} + 1`
+  __shunit_assertsSkipped=`expr "${__shunit_assertsSkipped}" + 1`
+  __shunit_assertsTotal=`expr "${__shunit_assertsTotal}" + 1`
 }
 
 # Prepare a script filename for sourcing.
@@ -975,7 +1006,7 @@ _shunit_prepForSourcing()
 #   string: with escaped character(s)
 _shunit_escapeCharInStr()
 {
-  \[ -n "$2" ] || return  # no point in doing work on an empty string
+  \[ -n "$2" ] || return  # No point in doing work on an empty string.
 
   # Note: using shorter variable names to prevent conflicts with
   # _shunit_escapeCharactersInString().
@@ -983,7 +1014,8 @@ _shunit_escapeCharInStr()
   _shunit_s_=$2
 
 
-  # escape the character
+  # Escape the character.
+  # shellcheck disable=SC1003,SC2086
   echo ''${_shunit_s_}'' |sed 's/\'${_shunit_c_}'/\\\'${_shunit_c_}'/g'
 
   unset _shunit_c_ _shunit_s_
@@ -997,7 +1029,7 @@ _shunit_escapeCharInStr()
 #   string: with escaped character(s)
 _shunit_escapeCharactersInString()
 {
-  \[ -n "$1" ] || return  # no point in doing work on an empty string
+  \[ -n "$1" ] || return  # No point in doing work on an empty string.
 
   _shunit_str_=$1
 
@@ -1023,6 +1055,7 @@ _shunit_extractTestFunctions() {
   # Extract the lines with test function names, strip of anything besides the
   # function name, and output everything on a single line.
   _shunit_regex_='^[ 	]*(function )*test[A-Za-z0-9_]* *\(\)'
+  # shellcheck disable=SC2196
   egrep "${_shunit_regex_}" "${_shunit_script_}" \
   |sed 's/^[^A-Za-z0-9_]*//;s/^function //;s/\([A-Za-z0-9_]*\).*/\1/g' \
   |xargs
@@ -1070,11 +1103,12 @@ noexec 2>/dev/null || _shunit_fatal \
 
 # We must manually source the tests in standalone mode.
 if \[ "${__shunit_mode}" = "${__SHUNIT_MODE_STANDALONE}" ]; then
+  # shellcheck disable=SC1090
   . "`_shunit_prepForSourcing \"${__shunit_script}\"`"
 fi
 
 # Configure default output coloring behavior.
-_shunit_configureColor ${SHUNIT_COLOR}
+_shunit_configureColor "${SHUNIT_COLOR}"
 
 # Execute the oneTimeSetUp function (if it exists).
 oneTimeSetUp
@@ -1087,7 +1121,7 @@ suite
 if \[ -z "${__shunit_suite}" ]; then
   shunit_funcs_=`_shunit_extractTestFunctions "${__shunit_script}"`
   for shunit_func_ in ${shunit_funcs_}; do
-    suite_addTest ${shunit_func_}
+    suite_addTest "${shunit_func_}"
   done
 fi
 unset shunit_func_ shunit_funcs_
@@ -1097,5 +1131,5 @@ oneTimeTearDown
 _shunit_generateReport
 
 # That's it folks.
-\[ ${__shunit_testsFailed} -eq 0 ]
+\[ "${__shunit_testsFailed}" -eq 0 ]
 exit $?
