added some new functions from shflags; increased output from some helpers

diff --git a/source/2.1/src/shunit2_test_helpers b/source/2.1/src/shunit2_test_helpers
--- a/source/2.1/src/shunit2_test_helpers
+++ b/source/2.1/src/shunit2_test_helpers
@@ -52,6 +52,15 @@ th_fatal() { echo "${MY_NAME}:FATAL $@" >&2; }
 # output subtest name
 th_subtest() { echo " $@" >&2; }
 
+th_oneTimeSetUp()
+{
+  # these files will be cleaned up automatically by shUnit2
+  stdoutF="${SHUNIT_TMPDIR}/stdout"
+  stderrF="${SHUNIT_TMPDIR}/stderr"
+  returnF="${SHUNIT_TMPDIR}/return"
+  expectedF="${SHUNIT_TMPDIR}/expected"
+}
+
 # generate a random number
 th_generateRandom()
 {
@@ -141,6 +150,8 @@ th_assertFalseWithOutput()
       "[ -s '${th_stdout_}' ]"
   assertFalse "${th_test_}; expected no output to STDERR" \
       "[ -s '${th_stderr_}' ]"
+  [ -s "${th_stdout_}" -a ! -s "${th_stderr_}" ] || \
+      _th_showOutput ${SHUNIT_FALSE} "${th_stdout_}" "${th_stderr_}"
 
   unset th_test_ th_rtrn_ th_stdout_ th_stderr_
 }
@@ -165,8 +176,48 @@ th_assertFalseWithError()
       "[ -s '${th_stdout_}' ]"
   assertTrue "${th_test_}; expected output to STDERR" \
       "[ -s '${th_stderr_}' ]"
+  [ ! -s "${th_stdout_}" -a -s "${th_stderr_}" ] || \
+      _th_showOutput ${SHUNIT_FALSE} "${th_stdout_}" "${th_stderr_}"
 
   unset th_test_ th_rtrn_ th_stdout_ th_stderr_
+}
+
+# Some shells, zsh on Solaris in particular, return immediately from a sub-shell
+# when a non-zero return value is encountered. To properly catch these values,
+# they are either written to disk, or recognized as an error the file is empty.
+th_clearReturn() { cp /dev/null "${returnF}"; }
+th_queryReturn()
+{
+  if [ -s "${returnF}" ]; then
+    th_return=`cat "${returnF}"`
+  else
+    th_return=${SHUNIT_ERROR}
+  fi
+}
+
+# Providing external and internal calls to the showOutput helper function.
+th_showOutput() { _th_showOutput $@; }
+_th_showOutput()
+{
+  _th_return_=$1
+  _th_stdout_=$2
+  _th_stderr_=$3
+
+  if [ ${_th_return_} != ${SHUNIT_TRUE} ]; then
+    if [ -n "${_th_stdout_}" -a -s "${_th_stdout_}" ]; then
+      echo '>>> STDOUT' >&2
+      cat "${_th_stdout_}" >&2
+    fi
+    if [ -n "${_th_stderr_}" -a -s "${_th_stderr_}" ]; then
+      echo '>>> STDERR' >&2
+      cat "${_th_stderr_}" >&2
+    fi
+    if [ -n "${_th_stdout_}" -o -n "${_th_stderr_}" ]; then
+      echo '<<< end output' >&2
+    fi
+  fi
+
+  unset _th_return_ _th_stdout_ _th_stderr_
 }
 
 #
